# Generated by Django 3.2.6 on 2021-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_leitura_resenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
