# Generated by Django 3.2.6 on 2021-11-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211105_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
