# Generated by Django 3.2.6 on 2021-11-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_leitura_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='resenha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
