# Generated by Django 3.2.6 on 2021-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leitura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
