# Generated by Django 3.2.6 on 2021-11-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
