# Generated by Django 3.2.6 on 2021-11-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_leitura_resenha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitura',
            name='livro',
        ),
        migrations.AddField(
            model_name='leitura',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.livro'),
        ),
    ]
